name: Terraform plan and test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Load Terraform Action Module"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform format"
      id: fmt
      run: terraform fmt -check -diff

    - name: "Terraform Init"
      id: init
      run: terraform init

    - name: "Terraform Plan"
      id: plan
      run: terraform plan -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
  

