name: Terraform destroy

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Load Terraform Action Module"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform destroy"
      id: destroy
      run: terraform destroy -auto-approve -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
