name: Terraform plan and test to Azure
          
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Terraform Init"
      uses: hashicorp/setup-terraform@v1
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "init"
    
    - name: "Terraform Apply"
      uses: hashicorp/setup-terraform@v1
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "apply"
        args: |
          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
          -var="client_id=${{ secrets.AZURE_CLIENT_ID }}"
          -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"

